---
functional:
  - пользователь должен иметь возможность искать товары по ключевому слову или категории
  - пользователь должен иметь возможность фильтровать товары
  - пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - сайт должен быть безопасным и защищать данные пользователя
  - сайт должен иметь мобильную версию
  - сайт должен быть доступен на различных устройствах
  - сайт должен быть протестирован на совместимость с последними версиями браузеров
  - сайт должен быть способен обрабатывать большое количество трафика
  - веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
implicit:
  - сайт должен иметь способность открываться на разных разрешениях и подстраиваться под них
  - пользователь должен иметь возможность зарегистрировать личный кабинет
  - в личном кабинете должны быть имя, фамилия, электронная почта, телефон, адрес, история заказов
  - пользователь должен иметь возможность выбрать то количество товаров, которое он хочет поместить в корзину
  - у пользователя должна быть возможность видеть количество добавленного в корзину товара в карточке самого товара
  - пользователь должен иметь возможность переходить на конкретную страницу с товарами
  - в фильтре Производитель должны быть только те, которые есть в выбранной категории
  - поиск должен работать по всем товарам, независимо от категории и страницы
  - при нажатии на кнопку оформить заказ в корзине открывается модальное окно с подтверждением заказа
  - в корзине при нажатии кнопки удалить открывается модальное окно с подтверждением удаления
  - в корзине должны корректно отображаться заголовки таблицы с товаром
  - пользователь должен иметь возможность выбрать валюту в которой отображается цена товара
  - пользователь должен иметь возможность выбрать язык в интернет-магазине
