---
functional:
  - пользователь должен иметь возможность искать товары по ключевому слову или категории
  - пользователь должен иметь возможность фильтровать товары
  - пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - сайт должен быть безопасным и защищать данные пользователя
  - сайт должен иметь мобильную версию
  - сайт должен быть доступен на различных устройствах
  - сайт должен быть протестирован на совместимость с последними версиями браузеров
  - сайт должен быть способен обрабатывать большое количество трафика
  - веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
implicit:
  - сайт должен иметь способность открываться на разных разрешениях и подстраиваться под них
  - в фильтре Производитель должны быть только те, которые есть в выбранной категории
  - при нажатии на кнопку оформить заказ в корзине открывается модальное окно с подтверждением заказа
  - пользователь должен иметь возможность выбрать язык в интернет-магазине
